#!/usr/bin/env bash

pushd ~/

sudo apt-get update

sudo apt-get install git-core

sudo apt-get install -y python-software-properties debconf-utils

# vim
sudo apt-get install vim
wget https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
mv basic.vim ~/.vimrc

# sublime
pushd ~/Downloads
wget https://download.sublimetext.com/sublime-text_build-3103_amd64.deb
sudo dpkg -i sublime-text_build-3103_amd64.deb

# java 8
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get update
echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
sudo apt-get install -y oracle-java8-installer

# sbt
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
sudo apt-get update
sudo apt-get install sbt

# bash stuff
pushd ~/
git clone git@github.com:queirozfcom/bash-configs.git
pushd bash-configs
utils/update-local-aliases
popd
popd

sudo apt-get install xubuntu-desktop
